# Generated by Django 4.0.4 on 2022-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='otherdetails',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='Department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
