# Generated by Django 4.0.4 on 2022-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_remove_employees_dateofjoining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('HiredeveloperId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(blank=True, max_length=500, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('JobTitle', models.CharField(blank=True, max_length=500, null=True)),
                ('Requirements', models.CharField(blank=True, max_length=250, null=True)),
                ('UploadFile', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='FirstName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='LastName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
