# Generated by Django 4.0.4 on 2022-06-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_bookspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookspace',
            name='PreferredTime',
        ),
    ]
