# Generated by Django 4.0.4 on 2022-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_remove_bookspace_preferredtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspace',
            name='PreferredTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
