# Generated by Django 4.0.4 on 2022-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_bookspace_preferredtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mmmh',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
